openapi: 3.1.0
info:
  title: Derolas Metrics API
  version: 1.0.0

paths:
  /volumes:
    get:
      summary: Volume by exchange and Derolas share
      operationId: getVolumes
      responses:
        "200":
          description: Time series volume data and derived exchange share metrics
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VolumesResponse"

  /pools:
    get:
      summary: List pools
      operationId: listPools
      responses:
        "200":
          description: All pools
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PoolSummary"

  /pools/{poolId}/metrics:
    get:
      summary: Metrics and time series for a pool
      operationId: getPoolMetrics
      parameters:
        - name: poolId
          in: path
          required: true
          schema:
            type: string
        - name: start
          in: query
          required: true
          description: Start of lookback window (inclusive)
          schema:
            type: string
            format: date-time
        - name: end
          in: query
          required: true
          description: End of lookback window (exclusive)
          schema:
            type: string
            format: date-time
        - name: resolution
          in: query
          required: false
          description: Aggregation granularity for charts
          schema:
            type: string
            enum: [1h,4h,1d]
            default: 1d
      responses:
        "200":
          description: Metrics for charts on the pool dashboard
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PoolMetricsResponse"

components:
  schemas:
    TimeSeriesPoint:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        value:
          type: number
      required: [timestamp, value]

    VolumesSeriesPoint:
      type: object
      properties:
        total_volume:
          type: number
          description: Total volume on venue over the window.
        derolas_volume:
          type: number
          description: Volume generated by Derolas over the window.
        derolas_volume_share_pct:
          type: number
          description: Percentage of venue volume that is Derolas (0–100)
        timestamp_start:
          type: string
          format: date-time
          description: Start of the time window (inclusive)
        timestamp_end:
          type: string
          format: date-time
          description: End of the time window (exclusive)
      required:
        - total_volume
        - derolas_volume
        - derolas_volume_share_pct

    VolumesResponse:
      type: object
      properties:
        series:
          # should be a dict of arrays of VolumesSeriesPoint
          type: object
          additionalProperties:
            type: array
            items:
              $ref: "#/components/schemas/VolumesSeriesPoint"
      required: [series]

    PoolSummary:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        chain:
          type: string
          example: base
        address:
          type: string
          description: On-chain pool address
        symbol:
          type: string
          description: Pool symbol / ticker
      required: [id, name, chain, address]

    AssetRoiSeries:
      type: object
      properties:
        asset_symbol:
          type: string
          example: wETH
        series:
          type: array
          items:
            $ref: "#/components/schemas/TimeSeriesPoint"
          description: Cumulative ROI (%) over time for this asset
      required: [asset_symbol, series]

    PoolMetricsResponse:
      type: object
      properties:
        pool_id:
          type: string
        current_apr:
          type: number
          description: Current APR (percentage, 0–100)
          example: 0.54
        fees_24h_usd:
          type: number
          example: 1.54
        total_shares:
          type: number
          example: 200.38
        tvl_usd:
          type: number
          description: Current total value locked
          example: 104497.48
        current_share_price_usd:
          type: number
          example: 521.49
        current_roi_pct:
          type: number
          description: Current ROI in percent (may be negative)
          example: -14.88
        share_price_series:
          type: array
          description: For "Derolas Share Price" chart
          items:
            $ref: "#/components/schemas/TimeSeriesPoint"
        asset_cumulative_roi_series:
          type: array
          description: For "Cumulative ROI of Assets in Bundle" multi-line chart
          items:
            $ref: "#/components/schemas/AssetRoiSeries"
        tvl_series:
          type: array
          description: TVL (USD) over previous 30 days
          items:
            $ref: "#/components/schemas/TimeSeriesPoint"
        fees_series:
          type: array
          description: Fees (USD) over previous 30 days
          items:
            $ref: "#/components/schemas/TimeSeriesPoint"
        lp_shares_series:
          type: array
          description: Derolas LP shares over previous 30 days
          items:
            $ref: "#/components/schemas/TimeSeriesPoint"
      required:
        - pool_id
        - current_apr
        - fees_24h_usd
        - total_shares
        - tvl_usd
        - current_share_price_usd
        - current_roi_pct
        - share_price_series
        - asset_cumulative_roi_series
        - tvl_series
        - fees_series
        - lp_shares_series
