# generated by datamodel-codegen:
#   filename:  open-api-spec.yaml
#   timestamp: 2025-11-30T21:02:12+00:00

from __future__ import annotations

from datetime import datetime
from typing import Dict, List, Optional

from pydantic import BaseModel, Field


class VolumesSeriesPoint(BaseModel):
    total_volume: float = Field(
        ..., description='Total volume on venue over the window.'
    )
    derolas_volume: float = Field(
        ..., description='Volume generated by Derolas over the window.'
    )
    derolas_volume_share_pct: float = Field(
        ..., description='Percentage of venue volume that is Derolas (0–100)'
    )
    timestamp_start: Optional[datetime] = Field(
        None, description='Start of the time window (inclusive)'
    )
    timestamp_end: Optional[datetime] = Field(
        None, description='End of the time window (exclusive)'
    )


class VolumesResponse(BaseModel):
    series: Dict[str, List[VolumesSeriesPoint]]


class PoolSummary(BaseModel):
    id: str
    name: str
    chain: str = Field(..., example='base')
    address: str = Field(..., description='On-chain pool address')
    symbol: Optional[str] = Field(None, description='Pool symbol / ticker')


class SharePricePoint(BaseModel):
    timestamp: datetime
    share_price_usd: float


class AssetRoiPoint(BaseModel):
    timestamp: datetime
    cumulative_roi_pct: float


class TvlPoint(BaseModel):
    timestamp: datetime
    tvl_usd: float


class FeesPoint(BaseModel):
    timestamp: datetime
    fees_usd: float


class LpSharesPoint(BaseModel):
    timestamp: datetime
    shares: float


class AssetRoiSeries(BaseModel):
    asset_symbol: str = Field(..., example='wETH')
    asset_name: Optional[str] = Field(None, description='Optional human-friendly label')
    series: List[AssetRoiPoint] = Field(
        ..., description='Cumulative ROI (%) over time for this asset'
    )


class PoolMetricsResponse(BaseModel):
    pool_id: str
    current_apr: float = Field(
        ..., description='Current APR (percentage, 0–100)', example=0.54
    )
    fees_24h_usd: float = Field(..., example=1.54)
    total_shares: float = Field(..., example=200.38)
    tvl_usd: float = Field(
        ..., description='Current total value locked', example=104497.48
    )
    current_share_price_usd: float = Field(..., example=521.49)
    current_roi_pct: float = Field(
        ..., description='Current ROI in percent (may be negative)', example=-14.88
    )
    share_price_series: List[SharePricePoint] = Field(
        ..., description='For "Derolas Share Price" chart'
    )
    asset_cumulative_roi_series: List[AssetRoiSeries] = Field(
        ..., description='For "Cumulative ROI of Assets in Bundle" multi-line chart'
    )
    tvl_series: List[TvlPoint] = Field(
        ..., description='TVL (USD) over previous 30 days'
    )
    fees_series: List[FeesPoint] = Field(
        ..., description='Fees (USD) over previous 30 days'
    )
    lp_shares_series: List[LpSharesPoint] = Field(
        ..., description='Derolas LP shares over previous 30 days'
    )
