/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
 
export type VolumesSeriesPoint = {
    /**
     * Total volume on venue over the window.
     */
    total_volume: number;
    /**
     * Volume generated by Derolas over the window.
     */
    derolas_volume: number;
    /**
     * Percentage of venue volume that is Derolas (0–100)
     */
    derolas_volume_share_pct: number;
    /**
     * Start of the time window (inclusive)
     */
    timestamp_start?: string;
    /**
     * End of the time window (exclusive)
     */
    timestamp_end?: string;
};

